### ISSUE TITLE
Glitchy and straight up doesn't work

### ISSUE THREAD

**Issue by ThatOneCalculator** [pipeseroni/pipesX.sh#3]
![image](https://user-images.githubusercontent.com/44733677/83931657-bee42100-a752-11ea-8dc9-303b984c995c.png)

**Comment by reportaman** [comment]
Same problem on my macOS Big Sur Apple M1

**Comment by poetaman** [comment]
Solved! Try changing the path at the top of the file /bin/bash to a newer version of bash. Essentially, edit the file to point to a new bash, run it & and if works then do make install again to copy it to a standard install directory. This resolved the problem at my end :)

**Comment by ThatOneCalculator** [comment]
Wow, I didn't expect a resolution on this 1 year old issue lol. I'll try it out when I can :)
